import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "/assets/img1.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img2.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img3.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img4.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img5.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img6.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img7.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img8.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img9.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img10.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img11.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img12.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img13.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
  {
    img: "/assets/img14.png",
    title: "EX DISPLAY : MSI Pro 16 Flex-036AU 15.6 MULTITOUCH All-In-On...",
    star: <AiFillStar className="rating-star" />,
    reviews: "(4 reviews)",
    prevPrice: "$499",
    newPrice: "$499",
    company: "MSI",
    color: "gray",
    stock: "in stock",
    category: "CUSTOM PCS",
  },
];

export default data;
